services:
  feature_engineering:
    build:
      context: .
      dockerfile: docker/feature_engineering/Dockerfile
    volumes:
      - ./data:/data
    container_name: feature_engineering_container
    command: ["python", "/app/feature_engineering.py"]

  training:
    build:
      context: .
      dockerfile: docker/training/Dockerfile
    volumes:
      - ./data:/data
    container_name: training_container
    command: ["python", "/app/training.py"]
    depends_on:
      - feature_engineering

  inference:
    build:
      context: .
      dockerfile: docker/inference/Dockerfile
    volumes:
      - ./data:/data
    container_name: inference_container
    command: ["python", "/app/inference.py"]
    depends_on:
      - training
